services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    IntelligentIntern\AzureBundle\Service\:
        resource: '../src/Service/*'
        public: true
        tags:
            - { name: 'ai.strategy' }
