services:
    IntelligentIntern\AzureBundle\Service\ChatCompletion\:
        resource: '../src/Service/ChatCompletion/*'
        public: true
        tags:
            - { name: 'chat_completion.strategy' }

    IntelligentIntern\AzureBundle\Service\Embedding\:
        resource: '../src/Service/Embedding/*'
        public: true
        tags:
            - { name: 'embedding.strategy' }

